spring.application.name=ReadVault

spring.datasource.url=jdbc:mysql://localhost:3306/infoynook?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Mummy@7835
# JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.servlet.multipart.max-file-size=4MB
spring.servlet.multipart.max-request-size=4MB

jwtSecretKey=dfsdf4ghsdf2ad5fdasf8d7adf2ads2ffgasdf5ad4f879dfa21df21af5fgv2fv1a5f4asfg323
